// src/app/_components/custom-sdk/widget/abc-text-customer-group-page-widget/abc-text-customer-group-page-widget.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import { Utils } from '@pega/angular-sdk-components';

interface AbcTextCustomerGroupPageWidgetProps {
  // If any, enter additional props that only exist on this component
  header?: string;
  description?: string;
  whatsnewlink?: string;
  label?: string;
  datasource?: any;
}

@Component({
  selector: 'app-abc-text-customer-group-page-widget',
  templateUrl: './abc-text-customer-group-page-widget.component.html',
  styleUrls: ['./abc-text-customer-group-page-widget.component.scss'],
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatTableModule]
})
export class AbcTextCustomerGroupPageWidgetComponent implements OnInit {
  @Input() pConn$: typeof PConnect;

  configProps$: AbcTextCustomerGroupPageWidgetProps;
  details$: any[];
  fields$: any[];
  displayedColumns: any[];

  workList: MatTableDataSource<any>;
  waitingForData = false;

  constructor(private utils: Utils) {}

  ngOnInit(): void {
    this.configProps$ = this.pConn$.getConfigProps();
    const { datasource } = this.configProps$;

    if (datasource?.source) {
      this.details$ = datasource.source.map(item => item.name);
    }

    // going to get data for worklist to put into a table
    // data comes from calling a PCore function to get
    // get data from a data page and a PConnect function
    // to get getContextName

    const dataViewName = 'D_pyMyWorkList';
    const context = this.pConn$.getContextName();
    this.waitingForData = true;
    const workListData = PCore.getDataApiUtils().getData(dataViewName, {}, context) as Promise<any>;

    workListData
      .then((response: any) => {
        if (response.data.data !== null) {
          this.fields$ = [
            {
              label: this.pConn$.getLocalizedValue('Case type', '', ''),
              type: 'TextInput',
              fieldName: 'pxProcessName'
            }, // 2nd and 3rd args empty string until typedef marked correctly
            {
              label: this.pConn$.getLocalizedValue('Key', '', ''),
              type: 'TextInput',
              fieldName: 'pxRefObjectInsName'
            }, // 2nd and 3rd args empty string until typedef marked correctly
            {
              label: this.pConn$.getLocalizedValue('Status', '', ''),
              type: 'TextInput',
              fieldName: 'pyAssignmentStatus'
            }, // 2nd and 3rd args empty string until typedef marked correctly
            {
              label: this.pConn$.getLocalizedValue('Stage', '', ''),
              type: 'TextInput',
              fieldName: 'pxTaskLabel'
            } // 2nd and 3rd args empty string until typedef marked correctly
          ];
          const tableDataResults = this.updateData(response.data.data, this.fields$);
          this.displayedColumns = this.getDisplayColumns(this.fields$);
          this.workList = new MatTableDataSource(tableDataResults);
          this.waitingForData = false;
        } else {
          this.workList = new MatTableDataSource();
          this.waitingForData = false;
        }
      })
      .catch((error: any) => {
        this.workList = new MatTableDataSource();
        this.waitingForData = false;
        console.log(error);
      });
  }

  updateData(listData: any[], fieldData: any[]): any[] {
    const returnList: any[] = new Array<any>();
    listData.forEach(row => {
      const rowData = JSON.parse(JSON.stringify(row));

      for (const field of fieldData) {
        const fieldName = field.fieldName;
        let formattedDate;

        switch (field.type) {
          case 'Date':
            formattedDate = this.utils.generateDate(rowData[fieldName], 'Date-Short-YYYY');
            rowData[fieldName] = formattedDate;
            break;
          case 'DateTime':
            formattedDate = this.utils.generateDateTime(rowData[fieldName], 'DateTime-Short-YYYY');
            rowData[fieldName] = formattedDate;
            break;
          default:
            break;
        }
      }
      returnList.push(rowData);
    });
    return returnList;
  }

  getDisplayColumns(fields: any[] = []) {
    return fields.map(field => {
      return field.fieldName;
    });
  }
}


<article class="psdk-announcement">
  <h2>{{ configProps$.header }}</h2>
  <div>
    <p>{{ configProps$.description }}</p>
    <div>
      <h3>{{ configProps$.label }}</h3>
      <ul>
        <li *ngFor="let detail of details$">{{ detail }}</li>
      </ul>
    </div>
  </div>
  <a *ngIf="configProps$.whatsnewlink != ''" mat-raised-button color="primary" [href]="configProps$.whatsnewlink">See what's new</a>
</article>
<br />
<table mat-table [dataSource]="workList">
  <ng-container *ngFor="let dCol of fields$" [matColumnDef]="dCol.fieldName">
    <th mat-header-cell *matHeaderCellDef>{{ dCol.label }}</th>
    <td mat-cell *matCellDef="let element">{{ element[dCol.fieldName] }}</td>
  </ng-container>

  <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
  <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
</table>

// src/app/_components/custom-constellation/widget/ABC_Text_CustomerGroupPageWidget/index.tsx
import { useEffect, useState } from 'react';
import { withConfiguration, Table } from '@pega/cosmos-react-core';
import { AppAnnouncement as PegaAppAnnouncement } from '@pega/cosmos-react-work';
import type { PConnFieldProps } from './PConnProps';
import './create-nonce';

import StyledAbcTextCustomerGroupPageWidgetWrapper from './styles';

// interface for props
interface AbcTextCustomerGroupPageWidgetProps extends PConnFieldProps {
  // If any, enter additional props that only exist on TextInput here
    datasource: Array<any>;
    header: string;
    description: string;
    whatsnewlink: string;
    image: string;
}

// props passed in combination of props from property panel (config.json) and run time props from Constellation
// any default values in config.pros should be set in defaultProps at bottom of this file
function AbcTextCustomerGroupPageWidget(props: AbcTextCustomerGroupPageWidgetProps) {

  const { header, description, datasource = [], whatsnewlink, image, getPConnect } = props;
  const [worklist, setWorklist] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const PConnect = getPConnect();
  const dataViewName = 'D_pyMyWorkList';
  const context = PConnect.getContextName();

  let details = [];
  // @ts-ignore
  if (datasource && datasource.source) {
    // @ts-ignore
    details = datasource.source.map((item) => {
      return item.name;
    });
  }

  // setting up columns for the work list table
  const columns = [
    { renderer: 'caseType', label: PConnect.getLocalizedValue('Case type', '', '') },
    { renderer: 'insKey', label: PConnect.getLocalizedValue('Key', '', '') },
    { renderer: 'status', label: PConnect.getLocalizedValue('Status', '', '') },
    { renderer: 'stage', label: PConnect.getLocalizedValue('Stage', '', '') }
  ];

  // going to get data for worklist to put into a table
  // data comes from calling a PCore function to get
  // get data from a data page and a PConnect function
  // to get getContextName
  useEffect(() => {

    PCore.getDataApiUtils()
      .getData(dataViewName, {}, context)
      // @ts-ignore
      .then((response: any) => {
        setIsLoading(false);
        if (response.data.data !== null) {
          // table requires an index or will get setExtraStackFrame error
          setWorklist(
            response.data.data.map((entry: any, index: number) => {
              // mapping the data into the column names
              // MUST have an id/index or will get a setExtraStackFrame error
              // put a key in the table
              return {
                caseType: entry.pxProcessName,
                insKey: entry.pxRefObjectInsName,
                status: entry.pyAssignmentStatus,
                stage: entry.pxTaskLabel,
                id: index
              };
            })
          );
        }
        else {
          setWorklist([]);
          setIsLoading(false);
        }

      })
      .catch((error: any) => {
        setWorklist([]);
        setIsLoading(false);
        console.log(error);
      });
  }, [context]);

  return (
    <StyledAbcTextCustomerGroupPageWidgetWrapper>
    <PegaAppAnnouncement
      heading={header}
      description={description}
      details={details}
      whatsNewLink={whatsnewlink}
      image={image.replace(/ /g, '+')}
    />
    <br />
    <Table
      title={PConnect.getLocalizedValue('Work list', '', '')}
      columns={columns}
      data={worklist}
      loading={isLoading}
      loadingMessage={PConnect.getLocalizedValue('Loading Work list', '', '')}
    />
    </StyledAbcTextCustomerGroupPageWidgetWrapper>
  );

}

export default withConfiguration(AbcTextCustomerGroupPageWidget);
